version: "3"

services:
  ######## APP ########
  dashboard-app:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    volumes:
      - ../:/var/www/app:cached
    ports:
      - 8088:8080

