name: Build package

on: [push, pull_request]

jobs:
  php-build:    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.0,8.1]
        laravel: [8.*]
        stability: [prefer-lowest, prefer-stable]                

    name: Test with PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, pcov
          coverage: pcov

      - name: Install Composer dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update --ansi
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction --ansi


      - name: Execute tests
        run: composer test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: .coverage/clover.xml
          fail_ci_if_error: true

  js-build:
    name: "Build frontend assets"
    needs: php-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2-beta

      - name: Install dependencies
        run: yarn install

      # Remove any commited assets before building.
      - name: Build frontend production assets
        run: |
          rm -rf /public/vendor/lighthouse-dashboard/js
          rm -rf /public/vendor/lighthouse-dashboard/css
          rm -rf /public/vendor/lighthouse-dashboard/fonts
          rm public/vendor/lighthouse-dashboard/mix-manifest.json
          yarn production

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: "Automated fresh build for frontend assets"
